"""empty message

Revision ID: 1e13b42bfe86
Revises: 7ec03ee0cca3
Create Date: 2023-05-11 14:30:43.499036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e13b42bfe86'
down_revision = '7ec03ee0cca3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
