"""empty message

Revision ID: 6949bfb9016b
Revises: 1e13b42bfe86
Create Date: 2023-05-14 16:49:36.810141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6949bfb9016b'
down_revision = '1e13b42bfe86'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
