"""empty message

Revision ID: 995fc95b2a5d
Revises: 6949bfb9016b
Create Date: 2023-05-16 11:21:30.312657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '995fc95b2a5d'
down_revision = '6949bfb9016b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('amount'),
    sa.UniqueConstraint('detail')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article')
    # ### end Alembic commands ###
