"""empty message

Revision ID: c27876e99e84
Revises: a13e72c4f486
Create Date: 2023-07-17 13:54:43.717865

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'c27876e99e84'
down_revision = 'a13e72c4f486'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('detail', table_name='article')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('detail', 'article', ['detail'], unique=False)
    # ### end Alembic commands ###
