"""empty message

Revision ID: e36c3b35bbc6
Revises: c27876e99e84
Create Date: 2023-07-22 09:26:19.261553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e36c3b35bbc6'
down_revision = 'c27876e99e84'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('follow_user', sa.Integer(), nullable=False),
    sa.Column('be_followed_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['be_followed_user'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follow_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follow')
    # ### end Alembic commands ###
